config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => {
    :sign_in => "login",
    :sign_out => "logout",
    :sign_up => "register"
  }
  get 'contact' => 'pages#contact'
  get 'country' => 'pages#country'
  resources :offers
  root 'offers#index'
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :read, :all
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/offer.rb
class Offer < ApplicationRecord
    has_one_attached :image, :dependent => :destroy

  validates :name, presence: true
  validates :description, presence: true
  validates :phone, presence: true
  validates :location, presence: true
  validates :meals, presence: true
  validates :host, presence: true
  validates :price, presence: true, :numericality => { :greater_than_or_equal_to => 1 }
  validates :stars, presence: true, :inclusion => 1..5
  validates :cleanliness, presence: true, :inclusion => 0..100
  validates :food, presence: true, :inclusion => 0..100
  validates :atmosphere, presence: true, :inclusion => 0..100

  def get_rating(offer)
    (offer.cleanliness + offer.food + offer.atmosphere) / 3
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  load_and_authorize_resource
  
  before_action :set_offer, only: %i[ show edit update destroy ]
  #def index
  #end
  

  # GET /offers or /offers.json
  def index
    @offers = Offer.all
  end

  # GET /offers/1 or /offers/1.json
  def show
  end

  # GET /offers/new
  def new
    @offer = Offer.new
  end

  # GET /offers/1/edit
  def edit
  end

  # POST /offers or /offers.json
  def create
    @offer = Offer.new(offer_params)

    respond_to do |format|
      if @offer.save
        format.html { redirect_to @offer, notice: "Offer was successfully created." }
        format.json { render :show, status: :created, location: @offer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offers/1 or /offers/1.json
  def update
    respond_to do |format|
      if @offer.update(offer_params)
        format.html { redirect_to @offer, notice: "Offer was successfully updated." }
        format.json { render :show, status: :ok, location: @offer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1 or /offers/1.json
  def destroy
    @offer.destroy
    respond_to do |format|
      format.html { redirect_to offers_url, notice: "Offer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer
      @offer = Offer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def offer_params
      params.require(:offer).permit(:name, :description, :price, :image, :location, :phone, :meals, :host, :stars, :rating, :cleanliness, :atmosphere, :food)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # GET /uers or /users.json
  def index
    @users = User.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TourismApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>

</html>

app/views/offers/_form.html.erb
<%= form_with(model: offer) do |form| %>
  <% if offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
        <% offer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :meals %>
    <%= form.text_field :meals %>
  </div>

  <div class="field">
    <%= form.label :host %>
    <%= form.text_field :host %>
  </div>

  <div class="field">
    <%= form.label :stars %>
    <%= form.text_field :stars %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.text_field :rating %>
  </div>

  <div class="field">
    <%= form.label :cleanliness %>
    <%= form.text_field :cleanliness %>
  </div>

  <div class="field">
    <%= form.label :atmosphere %>
    <%= form.text_field :atmosphere %>
  </div>

  <div class="field">
    <%= form.label :food %>
    <%= form.text_field :food %>
  </div>
  

  <div class="actions-button">
    <%= form.submit %>
  </div>
<% end %>

app/views/offers/edit.html.erb
<header class="main-header">
  <nav class="main-nav">
    <figure class="nav-logo">
      <a href="#"><%= image_tag("logo2.png", class: "logo inver-color", alt: "logo-image-small") %></a>
    </figure>
    <ul>
      <li><%= link_to root_path do %>Home<% end %></li>
      <li><a>|</a></li>
      <li><%= link_to contact_path do %>Contact<% end %></li>
      <% if current_user %>
        <li><a>|</a></li>
        <li><%= link_to destroy_user_session_path, method: :delete do %>Logout<% end %></li>
      <% else %>
        <li><a>|</a></li>
        <li><%= link_to new_user_session_path do %>Login<% end %></li>
      <% end %>
    </ul>
  </nav>
</header>
<main>
<hr id="horizontal-line">  
    <h1>Editing Offer</h1>

    <%= render 'form', offer: @offer %>
    <ul class="show-actions">
        <li><%= link_to '<button type="button">Back</button>'.html_safe, root_path %></li>
        <li><%= link_to '<button type="button">Show</button>'.html_safe, @offer %></li>
    </ul>  
</main>

app/views/offers/index.html.erb
<header class="main-header">
  <nav class="main-nav">
    <figure class="nav-logo">
      <a href="#"><%= image_tag("logo2.png", class: "logo inver-color", alt: "logo-image-small") %></a>
    </figure>
    <ul>
      <li><%= link_to root_path do %>Home<% end %></li>
      <li><a>|</a></li>
      <li><%= link_to contact_path do %>Contact<% end %></li>
      <% if current_user %>
        <li><a>|</a></li>
        <li><%= link_to destroy_user_session_path, method: :delete do %>Logout<% end %></li>
      <% else %>
        <li><a>|</a></li>
        <li><%= link_to new_user_session_path do %>Login<% end %></li>
      <% end %>
    </ul>
  </nav>
  <figure class="cover">
      <h1 class="motto">If not Now, When?</h1>
      <h2 class="sub">“Man cannot discover new oceans unless he has the courage to lose sight of the shore”</h2>
  </figure class="cover">
</header>

<main class="main-content">
  <h2>Check our Offers</h2>
  <section class="main-offers">
    <% @offers.each do |offer| %>
      <figure class="offer-container">
        <%= link_to offer do %>
          <% if offer.image.attached? %>
            <td><%= image_tag offer.image, class: "offers-photo" %></td>
          <% end %>
          <div class="offer-container-box">   
            <div class="offer-box-column">
              <strong><%= offer.location%></strong>
              <strong>$ <%= offer.price%> / night</strong>
            </div>
          </div>
        <% end %>
      </figure>
    <% end %>
  </section>
  <li><%= link_to '<button type="button">Click here to go in a land of magic </button>'.html_safe, country_path %></li>
</main>

<% if current_user && current_user.admin? %>
  <br><br>
  <p id="notice"><%= notice %></p>

  <h1>Edit your Offers</h1>
  <br><br>

  <table>
    <thead> 
      <tr>
        <th>Name</th>
        <th>Location</th>
        <th>Price</th>
        <th>Image</th>
        <th colspan="1"></th>
      </tr>
    </thead>

    <tbody>
      <% @offers.each do |offer| %>
        <tr class="edit">
          <td><%= offer.name %></td>
          <td><%= offer.location %></td>
          <td><%= offer.price %></td>
          <td><%= image_tag(offer.image.variant(resize: "100x100")) %></td>
          <td><%= link_to 'Show', offer %></td>
          <% if can? :edit, @offer %><td><%= link_to 'Edit', edit_offer_path(offer) %></td><% end %>
          <% if can? :delete, @offer %><td><%= link_to 'Destroy', offer, method: :delete, data: { confirm: 'Are you sure?' } %></td><% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <ul class="new_offer">
      <li><%= link_to '<button type="button">Add New Offer</button>'.html_safe, new_offer_path %></li>
      <li><%= link_to '<button type="button">See Users</button>'.html_safe, users_path %></li>
  </ul>  

<% end %>


<footer class="footer">
  <nav class="footer-nav">
    <ul>
      <li><a href="#"><%= image_tag("fb.png", alt: "facebook-logo", width: "50", height: "50")%></a></li>
      <li><a href="#"><%= image_tag("insta.png", alt: "instagram-logo", width: "50", height: "50")%></a></li>
      <li><a href="#"><%= image_tag("twitter.png", alt: "twitter-logo", width: "50", height: "50")%></a></li>
      <li><a href="#"><%= image_tag("wapp.png", alt: "wapp-logo", width: "50", height: "50")%></a></li>
      <li id="copyright">Copyright @2021</li>
    </ul>
  </nav>       
</footer>

app/views/offers/new.html.erb
<h1>New Offer</h1>

<%= render 'form', offer: @offer %>

<div class="links">
    <%= link_to 'Back', offers_path %>
</div>

app/views/offers/offer.html.erb
<header class="main-header">
    <nav class="main-nav">
        <figure class="nav-logo">
            <a href="#"><%= image_tag("logo2.png", class: "logo inver-color", alt: "logo-image-small") %></a>
        </figure>
        <ul>
            <li><a href="offers">Home</a></li>
            <li><a>|</a></li>
            <li><a href="contact.html">Contact</a></li>
        </ul>
    </nav>
    <figure class="cover">
        <h1 class="motto">If not Now, When?</h1>
       <h2 class="sub">“Man cannot discover new oceans unless he has the courage to lose sight of the shore”</h2>
    
    </figure class="cover">
</header>
<br><br>

app/views/offers/show.html.erb
<header class="main-header" id="anchorUp">
  <nav class="main-nav">
    <figure class="nav-logo">
      <a href="#"><%= image_tag("logo2.png", class: "logo inver-color", alt: "logo-image-small") %></a>
    </figure>
    <ul>
      <li><%= link_to root_path do %>Home<% end %></li>
      <li><a>|</a></li>
      <li><%= link_to contact_path do %>Contact<% end %></li>
      <% if current_user %>
        <li><a>|</a></li>
        <li><%= link_to destroy_user_session_path, method: :delete do %>Logout<% end %></li>
      <% else %>
        <li><a>|</a></li>
        <li><%= link_to new_user_session_path do %>Login<% end %></li>
      <% end %>
    </ul>
  </nav>
</header>

<main class="main-content-show">
  <hr id="horizontal-line">

  <section class="page-up">
    <section class="page">
      <section class="line">
        <strong> <%= @offer.location %> </strong>
      </section>
    <section class="resort">
      <h2> <%= @offer.name %> </h2>
      <section class="stars">
        <% for i in 1..5 do %>
          <% if i <= @offer.stars %>
            &#9733;
          <% else %>
            &#9734;
          <% end%>
        <% end %>
      </section>

      <section class="features">
        <div class="progress" data-label="Overall Rating">
          <span class="value" style="width:<%= @offer.get_rating(@offer) %>%;"></span>
        </div>
        <div class="progress" data-label="Cleanliness">
          <span class="value" style="width:<%= @offer.cleanliness %>%;"></span>
        </div>
        <div class="progress" data-label="Food">
          <span class="value" style="width:<%= @offer.food %>%;"></span>
        </div>
        <div class="progress" data-label="Atmoshpere">
          <span class="value" style="width:<%= @offer.atmosphere %>%;"></span>
        </div>
        <section class="description">
        <p>
          <%= @offer.description%>
        </p>
        </section>

      </section>
      
      <section class="details">
        <section class="price">
          <h2>$ <p id="offer-price"><%= @offer.price %><p> / night</h2>
        </section>
        <section class="host-details">
          <section class="details-item">
            <%= image_tag("host.png", alt: "host-logo", width: 50, height: 50)%>
            <div class="details-item-text">
              <h3>Your host</h3>
              <h3><%= @offer.host%></h3>
            </div>
          </section>
            <section class="details-item">
              <%= image_tag("hot.png", alt: "food-logo", width: 50, height: 50)%>
              <div class="details-item-text">
                <h3>Meal</h3>
                <h3><%= @offer.meals%></h3>
              </div>
            </section>
          </section>
        </section>
      </section>
     </section> 

      <hr id="horizontal-line">

      <section class="buttons">
        <section class="button-back">
            <%= link_to root_path do %>
            <%= image_tag("arrow.png", alt: "arrow-logo", width: 40, height: 40, class: "rotate180")%>
              <h3>Back to Resort Listing</h3>
          <% end %>
        </section>
         <hr id="horizontal-line">
        <section class="button-book">
          <a href="#anchor">
            <h3>Book a Room</h3>
            <%= image_tag("arrow.png", alt: "arrow-logo", width: 40, height: 40, class: "rotate90")%>
          </a>
        </section>
      </section>
    </section>
    <section class="buttons" id="anchor">
      <section class="button-back-resort displaynone">
       <a href="#anchorUp">
          <%= image_tag("arrow.png", alt: "arrow-logo", width: 40, height: 40, class: "rotate90")%>
         <h3>Back to Resort</h3>
        </a>
      </section>
    </section>

  <section class="page-down">
    <section class="line">
      <strong>Booking</strong>
    </section>
    <section class="resort">
      <h3>Book your room at</h3>
      <h2><%= @offer.name %></h2>
      <section class="stars">
        <% for i in 1..5 do %>
          <% if i <= @offer.stars %>
            &#9733;
          <% else %>
            &#9734;
          <% end%>
        <% end %>
      </section>

      <section class="main-content-form">
        <form name="contactForm">
          <div class="form-group">
            <label for="checkIn">Check In</label>
            <input
              id="checkIn"
              class="form-control"
              type="date"
              name="checkIn"
              onchange="handler1(event);"
              required
            />
          </div>

          <div class="form-group">
            <label for="checkOut">Check Out</label>
            <input
              id="checkOut"
              class="form-control"
              type="date"
              name="checkOut"
              onchange="handler2(event);"
              required
            />
          </div>

          <div class="form-group">
            <label for="firstName">First Name</label>
            <input
              id="firstName"
              class="form-control"
              type="text"
              name="firstName"
              placeholder="Jon"
              required
            />
          </div>

          <div class="form-group">
            <label for="lastName">Last Name</label>
            <input
              id="lastName"
              class="form-control"
              type="text"
              name="lastName"
              placeholder="Doe"
              required
            />
          </div>

          <div class="form-group">
            <label for="phone">Phone</label>
            <input
              id="phone"
              class="form-control"
              type="text"
              name="phone"
              placeholder="+40 731 660 186"
              required
            />
          </div>

          <div class="form-group">
            <label for="email">Email address</label>
            <input
              name="email"
              type="email"
              class="form-control"
              id="email"
              placeholder="name@example.com"
              required
            />
          </div>

          <div class="form-group">
            <label for="attendees">Scope</label>
            <select class="form-control" id="attendees" name="attendees">
              <option value="0">Not specified</option>
              <option value="1">Business</option>
              <option value="2">Leisure</option>
            </select>
          </div>

          <div class="form-group">
            <label for="message">Message (optional)</label>
            <textarea
              id="message"
              class="form-control"
              name="message"
              placeholder="I want a room with a better view .."
              rows="10"
              cols="40">
            </textarea>
          </div>

          <div id="errorAlert" class="error"></div>

          <div class="form-group">
            <button type="button" class="btn btn-primary">
              Submit
            </button>
          </div>
        </form>

        <div id="successMessage" class="success hidden">
          Booking request successfully sent!
        </div>
      </section>
    </section>

    <section class="details">
      <section class="price" id="total-price">
        <p>$ <strong id="trip-price"></strong> / trip</p>
        <p><strong id="nights"></strong> nights</p>
      </section>
      <section class="host-details">
        <section class="details-item">
          <%= image_tag("host.png", alt: "host", width: 50, height: 50)%>
          <div class="details-item-text">
            <h3>Your host</h3>
            <h3><%= @offer.host%></h3>
          </div>
        </section>
        <section class="details-item">
          <%= image_tag("hot.png", alt: "food-logo", width: 50, height: 50)%>
          <div class="details-item-text">
            <h3>Meals</h3>
            <h3><%= @offer.meals%></h3>
          </div>
        </section>
      </section>
    </section>
  </section>

  <section class="buttons" id="button-hidden">
    <section class="button-back-resort">
      <a href="#anchorUp">
        <%= image_tag("arrow.png", alt: "icon-arrow", width: 40, height: 40, class: "rotate270")%>
        <h3>Back to Resort</h3>
      </a>
    </section>
  </section>
  
  <section class="contact-us-show">
    <hr id="horizontal-line">
    <h2>Contact Us</h2>
    <section class="contact-item">
      <div class="icon">
        <a href="#"><%= image_tag("call.png", alt: "call-logo", width: "50", height: "50")%></a>
      </div>
      <a href="tel:+123456789012"><%= @offer.phone %></a>
    </section>
  </section>
</main>

<% if current_user && current_user.admin? %>
  <ul class="show-actions">
    <li><%= link_to '<button type="button">Back</button>'.html_safe, root_path %></li>
    <li><%= link_to '<button type="button">Edit</button>'.html_safe, edit_offer_path(@offer) %></li>
  </ul>  
<% end %>

<footer class="footer">
  <nav class="footer-nav">
    <ul>
      <li><a href="#"><%= image_tag("fb.png", alt: "facebook-logo", width: "50", height: "50")%></a></li>
      <li><a href="#"><%= image_tag("insta.png", alt: "instagram-logo", width: "50", height: "50")%></a></li>
      <li><a href="#"><%= image_tag("twitter.png", alt: "twitter-logo", width: "50", height: "50")%></a></li>
      <li><a href="#"><%= image_tag("wapp.png", alt: "wapp-logo", width: "50", height: "50")%></a></li>
      <li id="copyright">Copyright @2021</li>
    </ul>
  </nav>      
</footer>

<%= javascript_include_tag 'offer'%>

app/views/pages/contact.html.erb
<header class="main-header">
  <nav class="main-nav">
    <figure class="nav-logo">
      <a href="#"><%= image_tag("logo2.png", class: "logo inver-color", alt: "logo-image-small") %></a>
    </figure>
    <ul>
      <li><%= link_to root_path do %>Home<% end %></li>
      <% if current_user %>
        <li><a>|</a></li>
        <li><%= link_to destroy_user_session_path, method: :delete do %>Logout<% end %></li>
      <% else %>
        <li><a>|</a></li>
        <li><%= link_to new_user_session_path do %>Login<% end %></li>
      <% end %>
    </ul>
  </nav>
</header>

<main>
    <hr id="horizontal-line">
    <section class="contact">
        <div class="content">
            <h2>Contact US</h2>
            <p>If you have any questions, we are open for many suggestions or just to have a chat.</p>
        </div>
        <div class="container">
            <div class="contact-info">
                <div class="box">
                    <div class="icon"><a href="#"><%= image_tag("map.png", alt: "map-logo", width: "50", height: "40")%></a></div>
                    <div class="text">
                        <h3>Address</h3>
                        <p>Dorm 9C,<br>Student Alley,<br>Timisoara, Romania</p>
                    </div>
                </div>
                <div class="box">
                    <div class="icon"><a href="#"><%= image_tag("call.png", alt: "call-logo", width: "50", height: "50")%></a></div>
                    <div class="text">
                        <h3>Phone</h3>
                        <p>+4072134567</p>
                    </div>
                </div>
                <div class="box">
                    <div class="icon"><a href="#"><%= image_tag("message.png", alt: "mail-logo", width: "50", height: "50")%></a></div>
                    <div class="text">
                        <h3>Email</h3>
                        <p>tourism_contact@gmail.com</p>
                    </div>
                </div>
            </div>
            <div class="mapping"><iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2784.0605533186176!2d21.23823531536105!3d45.74993197910532!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47455d8860cf92c9%3A0xdb3521f21f643d9e!2sParcare%2C%20Aleea%20Studen%C8%9Bilor%209%2C%20Timi%C8%99oara!5e0!3m2!1sen!2sro!4v1635181152419!5m2!1sen!2sro"
             width="400" height="300" style="border:0;" allowfullscreen="" loading="lazy"></iframe></div>
            <div class ="contactForm">
                <form>
                    <h2>Send us a message</h2>
                    <div class="inputBox">
                        <input type="text" name="" required="required">
                        <span>Name</span>
                    </div>
                    <div class="inputBox">
                        <input type="text" name="" required="required">
                        <span>Email</span>
                    </div>
                    <div class="inputBox">
                        <textarea required="required"></textarea>
                        <span>Type your message here.</span>
                    </div>
                    <div class="inputBox">
                        <input type="submit" name="" value="Send">
                    </div>
                </form>
            </div>
        
        </div>    

    </section>


</main>

 <footer class="footer">
  <nav class="footer-nav">
        <ul>
            <li><a href="#"><%= image_tag("fb.png", alt: "facebook-logo", width: "50", height: "50")%></a></li>
            <li><a href="#"><%= image_tag("insta.png", alt: "instagram-logo", width: "50", height: "50")%></a></li>
            <li><a href="#"><%= image_tag("twitter.png", alt: "twitter-logo", width: "50", height: "50")%></a></li>
            <li><a href="#"><%= image_tag("wapp.png", alt: "wapp-logo", width: "50", height: "50")%></a></li>
            <li id="copyright">Copyright @2021</li>
        </ul>
    </nav>
           
 </footer>

app/views/users/index.html.erb
<header class="main-header">
  <nav class="main-nav">
    <figure class="nav-logo">
      <a href="#"><%= image_tag("logo2.png", class: "logo inver-color", alt: "logo-image-small") %></a>
    </figure>
    <ul>
      <li><%= link_to root_path do %>Home<% end %></li>
      <li><a>|</a></li>
      <li><%= link_to contact_path do %>Contact<% end %></li>
      <% if current_user %>
        <li><a>|</a></li>
        <li><%= link_to destroy_user_session_path, method: :delete do %>Logout<% end %></li>
      <% else %>
        <li><a>|</a></li>
        <li><%= link_to new_user_session_path do %>Login<% end %></li>
      <% end %>
    </ul>
  </nav>
  <hr id="horizontal-line">
</header>

<main class="main-user">
    <br>

    <% @users.each do |user| %> 
        <div>
            <%= user.email %>
            <%= user.encrypted_password %>
        </div>
    <% end %>
</main>